### PR TITLE
Migrate use cases from use case repo

### PR DESCRIPTION
**Pull request by rikoe**
- Copy use case markdown files and related images from FDC3/use-cases to FDC3/FDC3
- Update navigation sidebar to reflect new use cases
- Give new use cases ids and sidebar labels
- Shorten use case ids
- Add status section at top of each use case
- Remove status field from header at top of each use case (caused a build warning)
- Rename intro to overview
- Show use cases all in one true, don’t use sub-sections in navigation side-bar

### CODE REVIEW

**Comment by saori-tr** [comment]
@rikoe could you please resolve the conflict on website/siteConfig.js?

**Comment by rikoe** [comment]
@saori-tr I have removed the conflicts now.

I have also removed the "Accepted" banner across the top of the use cases, I think if only accepted use cases are included it is not necessary.

We do need to decided what to do about use case 6 though (see https://fdc3-use-cases.finos.org/2018/11/07/006-dynamic-discovery-in-chat.html). It is labelled as "In review" in the use cases repo.

You also previously mentioned a use case 15, I don't see one...

Finally, do we need the dates in the use case document names (e.g. "2018-06-08-001-equity-sell-side-trader.md") - in my opinion it would all be much simpler to work with if there was no date in the name, e.g. "uc-1-equity-sell-side-trader.md".

Example of how it will look once merged is here: https://rikoe.github.io/FDC3/docs/use-cases/overview

**Comment by nkolba** [comment]
Looks Good to Me

**Comment by saori-tr** [comment]
@rikoe:

Will wait for you on the intro.md conflict.  

Please ignore UC 15 for now, we will add it later (after this merge/before launch).

Are you able to just simply remove (not bring in) UC 6?  Could you please?

Thanks.

**Comment by rikoe** [comment]
@saori-tr @nkolba I have merged in latest changes and also removed use case 6 entirely. Hope it is good for merge now!

**Pull request merged**
