### PR TITLE
Fixed a few typos

### PR DESCRIPTION
**Pull request by jrhenderson1988**

### CODE REVIEW

**Comment by finos-admin** [comment]
Thank you for your pull request and welcome to our community! We require contributors to sign a [Contributor License Agreement](https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/75530375/Legal+Requirements#LegalRequirements-ContributorLicenseAgreement) and we don't seem to have CLAs on file for these contributors to the Pull Request: (@jrhenderson1988). In order for your PR to be reviewed and merged, please follow the directions at the link above.

Project team: please **do not merge this Pull Request** until Foundation staff have confirmed that a CLA is in place for the new contributor(s) listed above.

If there are any questions, please don't hesitate to [get in touch with our Infrastructure Support team](https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/77955298/Getting+in+Touch#GettinginTouch-InfrastructureSupport). /CC @finos-admin

**Comment by ColinEberhardt** [comment]
@maoo can you please add @jrhenderson1988 to the contributors list?

**Comment by rikoe** [comment]
@ColinEberhardt according to @maoo we don't need CLA approval for documentation updates, and we can manually add the cla-present label and merge such PRs. (This is what was behind my cla-bot issue the other day...)

I think we need some more clarification though as to when and when not CLA approval is required, a blanket policy seems easier.

**Comment by ColinEberhardt** [comment]
Considering that the documentation is part of the artefact that is distributed artefact, I’m surprised that a CLA isn’t needed.

Having said that, I’m all for keeping process light and reducing friction!

**Comment by finos-admin** [comment]
@jrhenderson1988 is covered by ScottLogic CCLA, I'm manually adding `cla-present` label and removing CLA bot comment, while we work to update CLA configuration and prevent this to happen for future PRs. 

This Pull Request can be merged.

Thank you for the contribution, and apologies for the confusion.

-- from @maoo

**Comment by ColinEberhardt** [comment]
@rikoe based on the above, are you happy to merge?

**Comment by rikoe** [comment]
Yes! Let's do it.

**Pull request merged**
